name: Build and Push image to Hub

on:
    push:
        branches:
            - main
        
jobs:
    run_migrations:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Check for migration changes
              uses: dorny/paths-filter@v3
              id: changes
              with:
                filters: |
                  migrations:
                    - 'prisma/migrations/**'

            - name: Setup Node
              if: steps.changes.outputs.migrations == 'true'
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Install Dependencies
              if: steps.changes.outputs.migrations == 'true'
              run: npm install

            - name: Run Migrations
              if: steps.changes.outputs.migrations == 'true'
              run: npx prisma migrate deploy
              env:
                DATABASE_URL: ${{ secrets.DATABASE_URL }}


    build_and_push:
        needs: run_migrations
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Checkout Code
              uses: actions/checkout@v5
            
            - name: Docker Buildx
              uses: docker/setup-buildx-action@v3

            # - name: QEMU
            #   uses: docker/setup-qemu-action@v3

            - name: Build and Push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: sreesen/flag0ut:latest
                build-args: |
                    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
                    NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }}NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL }}NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL }}
                    REDIS_URL=${{ secrets.REDIS_URL }}